# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d4782e1f37a4d10edc90a3c08dcb961bf9b61578e3ac1076681d17a389045e29752886fd56a6c9a8c3dc5fe045bcdab8361c31fed085e1e0bcd45a6301b52cb

test:
  secret_key_base: 933bc5338a7d83dfd616f878b8125bd3ab921220de97285bfefcef6843669644605d24ad6a3dd69409770f4aa5637aae6bc75ac48816b68412250e5227188428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
